vi.mock('./components/views/McpSettings', () => ({ McpSettings: () => null }));
import { render, screen, fireEvent, waitFor, act, renderHook, cleanup } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { SettingsView } from './components/views/SettingsView';
import { useDragDrop } from './hooks/useDragDrop';
import { useAudioSearch } from './hooks/useAudioSearch';
import type { Source } from './types';
const invoke=vi.fn();
let listener: (event: {payload:{type:string;paths:string[]}})=>void;
vi.mock('@tauri-apps/api/core',()=>({isTauri:()=>true,invoke:(...args:unknown[])=>invoke(...args)}));
vi.mock('@tauri-apps/api/webviewWindow',()=>({getCurrentWebviewWindow:()=>({onDragDropEvent:vi.fn((fn)=>{listener=fn;return Promise.resolve(vi.fn());})})}));
const source:Source={id:'scope',name:'Recordings',root:'/audio',generation:0,available:true,scope:'files',files:[{relative_path:'one.wav',sound_id:'one',status:'missing'},{relative_path:'two.wav',sound_id:'two',status:'ready'}]};
beforeEach(()=>{invoke.mockReset();invoke.mockImplementation((command:string)=>Promise.resolve(command==='jobs'||command==='sources'?[]:command==='search_sounds'?{items:[],total:0,interpretation:{terms:[],excluded:[],corrected:[]}}:null));});
afterEach(cleanup);
describe('scoped imports',()=>{
 it('continues after individual drop errors and deduplicates exact paths',async()=>{const importPath=vi.fn(async(path:string)=>{if(path.endsWith('.txt'))throw new Error('Unsupported audio extension');});const error=vi.fn();renderHook(()=>useDragDrop(importPath,error));await waitFor(()=>expect(listener).toBeDefined());await act(async()=>listener({payload:{type:'drop',paths:['/a.txt','/one.wav','/one.wav','/two.wav']}}));expect(importPath.mock.calls.map(c=>c[0])).toEqual(['/a.txt','/one.wav','/two.wav']);expect(error).toHaveBeenLastCalledWith(expect.stringContaining('/a.txt: Error: Unsupported audio extension'));});
 it('rejects oversized drops before importing anything',async()=>{const importPath=vi.fn();const error=vi.fn();renderHook(()=>useDragDrop(importPath,error));await act(async()=>listener({payload:{type:'drop',paths:Array.from({length:257},(_,i)=>`/${i}.wav`)}}));expect(importPath).not.toHaveBeenCalled();expect(error).toHaveBeenCalledWith('Drop up to 256 paths at a time');});
 it('stops drop submission when unmounted',async()=>{let finish!:()=>void;const importPath=vi.fn(()=>new Promise<void>(resolve=>{finish=resolve;}));const {unmount}=renderHook(()=>useDragDrop(importPath,vi.fn()));await act(async()=>listener({payload:{type:'drop',paths:['/one.wav','/two.wav']}}));unmount();await act(async()=>finish());expect(importPath).toHaveBeenCalledTimes(1);});
 it('file picker submits only selected files and reports failures without aborting',async()=>{invoke.mockImplementation((cmd:string,args?:{path:string})=>{if(cmd==='choose_files')return Promise.resolve(['/bad.txt','/one.wav','/one.wav']);if(cmd==='import_path'&&args?.path==='/bad.txt')return Promise.reject('Unsupported audio extension');return Promise.resolve(cmd==='jobs'||cmd==='sources'?[]:null);});const {result}=renderHook(()=>useAudioSearch('library',undefined,vi.fn()));await act(async()=>{await result.current.addFiles();});expect(invoke.mock.calls.filter(c=>c[0]==='import_path').map(c=>c[1])).toEqual([{path:'/bad.txt'},{path:'/one.wav'}]);expect(result.current.error).toContain('/bad.txt: Unsupported audio extension');});
});
describe('source scope controls',()=>{
 const show=()=>render(<SettingsView roots={[source]} onRescan={vi.fn()} onRelink={vi.fn()} onError={vi.fn()} />);
 it('shows explicit scope and each file availability',()=>{show();expect(screen.getByText(/Selected files only/)).toBeInTheDocument();expect(screen.getByText('one.wav')).toBeInTheDocument();expect(screen.getByText(/missing/)).toBeInTheDocument();expect(screen.getByText(/ready/)).toBeInTheDocument();});
 it('requires confirmation to broaden a scope and cancel keeps it unchanged',async()=>{show();fireEvent.click(screen.getByText('Import entire folder'));expect(screen.getByRole('dialog')).toHaveTextContent('siblings');expect(invoke).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Cancel'));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Import entire folder'));fireEvent.click(screen.getByText('Confirm'));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('convert_source',{id:'scope',confirmed:true}));});
 it('explains metadata removal and confirms before deleting',async()=>{show();fireEvent.click(screen.getByText('Remove source'));expect(screen.getByRole('dialog')).toHaveTextContent('annotations and clip recipes');expect(invoke).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Confirm'));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('remove_source',{id:'scope',confirmed:true}));});
 it('relinks the selected sound rather than granting its parent folder',async()=>{invoke.mockResolvedValueOnce('/new/renamed.wav').mockResolvedValueOnce(source);show();fireEvent.click(screen.getByRole('button',{name:'Relink one.wav'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('relink_file',{id:'one',path:'/new/renamed.wav'}));});
 it('keeps confirmation keyboard focus inside and Escape cancels',()=>{show();const opener=screen.getByText('Remove source');opener.focus();fireEvent.click(opener);const cancel=screen.getByText('Cancel');expect(cancel).toHaveFocus();fireEvent.keyDown(cancel,{key:'Tab'});expect(screen.getByText('Confirm')).toHaveFocus();fireEvent.keyDown(screen.getByText('Confirm'),{key:'Tab',shiftKey:true});expect(cancel).toHaveFocus();fireEvent.keyDown(cancel,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(opener).toHaveFocus();expect(invoke).not.toHaveBeenCalled();});
 it('pages large scopes while preserving exact availability',()=>{const root={...source,files:Array.from({length:101},(_,i)=>({relative_path:`${i}.wav`,sound_id:null,status:i===100?'missing':'ready'}))};render(<SettingsView roots={[root]} onRescan={vi.fn()} onRelink={vi.fn()} onError={vi.fn()} />);expect(screen.queryByText('100.wav')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Next files'));expect(screen.getByText('100.wav')).toBeInTheDocument();expect(screen.getByText(/missing/)).toBeInTheDocument();expect(screen.queryByText('0.wav')).not.toBeInTheDocument();});

});
