import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { McpSettings } from './components/views/McpSettings';
import { call } from './api';
vi.mock('./api', () => ({ call: vi.fn() }));
const mock = vi.mocked(call);
beforeEach(() => mock.mockReset());
it('starts only by explicit action and pairs/revokes an individual client', async () => {
  const stopped = { endpoint: null, clients: [] };
  const client = { id: 'editor', name: 'Editor' };
  const running = { endpoint: 'http://127.0.0.1:1234/mcp', clients: [] };
  mock.mockResolvedValueOnce(stopped).mockResolvedValueOnce(running).mockResolvedValueOnce({ client, token: 'private-token' }).mockResolvedValueOnce({ ...running, clients: [client] }).mockResolvedValueOnce(running).mockResolvedValueOnce(stopped);
  render(<McpSettings onError={vi.fn()} />);
  await waitFor(() => expect(mock).toHaveBeenCalledTimes(1));
  expect(mock).toHaveBeenCalledWith('mcp_status');
  fireEvent.click(screen.getByText('Start MCP'));
  await screen.findByText('Running');
  fireEvent.change(screen.getByLabelText('Client name'), { target: { value: 'Editor' } });
  fireEvent.click(screen.getByText('Pair client'));
  expect(await screen.findByLabelText('MCP client configuration')).toHaveTextContent('private-token');
  const copy = vi.fn().mockResolvedValue(undefined);
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: copy } });
  fireEvent.click(screen.getByText('Copy configuration'));
  await waitFor(() => expect(copy).toHaveBeenCalledWith(expect.stringContaining('Bearer private-token')));
  fireEvent.click(screen.getByText('Revoke Editor'));
  await waitFor(() => expect(screen.queryByLabelText('MCP client configuration')).toBeNull());
  expect(mock).toHaveBeenCalledWith('mcp_revoke', { id: 'editor' });
  fireEvent.click(screen.getByText('Stop MCP'));
  await screen.findByText('Stopped');
});
it('reports start failure without claiming to run, and rejects invalid ports', async () => {
  const error = vi.fn();mock.mockResolvedValueOnce({ endpoint: null, clients: [] }).mockRejectedValueOnce(new Error('Port unavailable'));
  render(<McpSettings onError={error} />);
  await waitFor(() => expect(mock).toHaveBeenCalledTimes(1));
  fireEvent.change(screen.getByLabelText('MCP port'), { target: { value: '65536' } });
  expect(screen.getByText('Start MCP')).toBeDisabled();
  fireEvent.change(screen.getByLabelText('MCP port'), { target: { value: '1234' } });
  fireEvent.click(screen.getByText('Start MCP'));
  await waitFor(() => expect(error).toHaveBeenCalledWith('Error: Port unavailable'));
  expect(screen.getByText('Stopped')).toBeInTheDocument();
});
it('pairs only selected sources with separate write/path/export grants and native destination approval', async () => {
  const access = { source_ids: ['public'], read: true, edit: false, export: true, paths: false };
  const client = { id: 'editor', name: 'Editor', access };
  const running = { endpoint: 'http://127.0.0.1:1234/mcp', clients: [] };
  mock.mockResolvedValueOnce(running).mockResolvedValueOnce({ client, token: 'token' }).mockResolvedValueOnce({ ...running, clients: [client] }).mockResolvedValueOnce({ id: 'grant', path: '/approved/clip.wav' });
  const source = { id: 'public', name: 'Public recordings', root: '/public', generation: 0, available: true, scope: 'folder' as const, files: [] };
  render(<McpSettings roots={[source]} onError={vi.fn()} />);
  await screen.findByText('Running');
  expect(screen.getByLabelText('Edit annotations and clips')).not.toBeChecked();
  expect(screen.getByLabelText('Export clips to approved destinations')).not.toBeChecked();
  expect(screen.getByLabelText('Reveal local paths')).not.toBeChecked();
  fireEvent.change(screen.getByLabelText('Client name'), { target: { value: 'Editor' } });
  fireEvent.click(screen.getByLabelText('Public recordings'));
  fireEvent.click(screen.getByLabelText('Export clips to approved destinations'));
  fireEvent.click(screen.getByText('Pair client'));
  await screen.findByText('Approve WAV destination for Editor');
  expect(mock).toHaveBeenCalledWith('mcp_pair', { name: 'Editor', access });
  fireEvent.click(screen.getByText('Approve WAV destination for Editor'));
  await screen.findByText('/approved/clip.wav');
  expect(mock).toHaveBeenCalledWith('mcp_approve_destination', { clientId: 'editor', format: 'wav' });
  expect(screen.getByText('grant')).toBeInTheDocument();
});
it('shows the installed absolute bridge location without workspace or PATH discovery', async () => {
  mock.mockResolvedValueOnce({ endpoint: null, clients: [] }).mockResolvedValueOnce({ command: '/Applications/CreativeShelf.app/Contents/Resources/mcp/soundshelf-mcp', discovery: '/private-library/runtime/mcp.json' });
  render(<McpSettings onError={vi.fn()} />);
  await waitFor(() => expect(mock).toHaveBeenCalledTimes(1));
  fireEvent.click(screen.getByText('Show installed bridge'));
  expect(await screen.findByLabelText('Installed MCP bridge configuration')).toHaveTextContent('/Applications/CreativeShelf.app/Contents/Resources/mcp/soundshelf-mcp');
  expect(mock).toHaveBeenCalledWith('mcp_bridge_location');
  expect(screen.getByText('Stopped')).toBeInTheDocument();
});
